### ISSUE TITLE
Bilingual Dictionaries support

### ISSUE THREAD

**Issue by Deviant5186** [fkolcu/cambridge-dictionary-ffextension#1]
Hi, I wonder is there any method to change the default dictionary to a Bilingual Dictionaries, such as English-Chinese-simplified.
Here is a link for example:
https://dictionary.cambridge.org/dictionary/english-chinese-simplified/example
Thank you for your great work.

**Comment by fkolcu** [comment]
Hi, currently, there is no option to do that. However, it would be great to add that option to the addon. When I find an availability I will look into that.

And thank you for sharing this valuable idea.
