### ISSUE TITLE
Click the add-on icon on the bar not work as expected

### ISSUE THREAD

**Issue by Deviant5186** [fkolcu/cambridge-dictionary-ffextension#2]
it says:

Firefox Can’t Open This Page
To protect your security, dictionary.cambridge.org will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

<img width="717" alt="Screenshot 2023-08-04 at 10 24 01 PM" src="https://github.com/fkolcu/cambridge-dictionary-ffextension/assets/117066658/847676e3-772b-413e-b4a4-fcb9f734782e">

**Comment by fkolcu** [comment]
Firefox is blocking the webpage from opening in a frame. To resolve the problem, I'll find an alternative solution or workaround

**Comment by fkolcu** [comment]
The new version 3.2 is now live. After updating the addon to 3.2, the problem will be gone.
