### ISSUE TITLE
Unable to zoom

### ISSUE THREAD

**Issue by wojtulace** [fkolcu/cambridge-dictionary-ffextension#3]
Hello,

I think your add-on is great. However, I have one issue - the text is too small for me. The default zoom-in function provided by the browser does not work due to the nature of an iframe.  Is there any possibility to solve this?

**Comment by fkolcu** [comment]
Hello, thank you for taking the time to report this.

I will check what I can do about this.

**Comment by fkolcu** [comment]
I have added support for increasing text size, and this feature will be live anytime soon.

**Comment by wojtulace** [comment]
Thank you. The update works great. 

I use my TV as a monitor and sit in a certain distance to it. Therefore, I need the text enlarged to be comfortable to read.
